data_options:
    train:
        batch_size: 8
        buffer_size: 1024
        normalize_exams: true
        output_size: [256, 256]
        slice_types: ['TRA', 'ADC', 'DWI', 'DCEE', 'DCEL', 'label']
        augment_options:
            random_crop:
            random_flip:
            random_contrast:
            random_warp:
    eval:
        batch_size: 64
        output_size: [256, 256]
        slice_types: ['TRA', 'ADC', 'DWI', 'DCEE', 'DCEL', 'label']
