deploy_options.metrics:
    - Precision:
        thresholds: 0.80
        name: "pixel/precision"
    - Recall:
        thresholds: 0.80
        name: "pixel/recall"
    - AUC:
        curve: "PR"
        name: "pixel/AUPRC"
    - AUC:
        curve: "ROC"
        name: "pixel/AUROC"
    - FBetaScore:
        thresholds: 0.80
        beta: 1.0
        name: "pixel/F1-score"
    - FBetaScore:
        thresholds: 0.80
        beta: 2.0
        name: "pixel/F2-score"
    - RegionBasedPrecision:
        thresholds: 0.80
        IoU_threshold: 0.30
        resize_factor: 0.5
        name: "region/precision"
    - RegionBasedRecall:
        thresholds: 0.80
        IoU_threshold: 0.30
        resize_factor: 0.5
        name: "region/recall"
    - RegionBasedTruePositives:
        thresholds: 0.80
        IoU_threshold: 0.30
        resize_factor: 0.5
        name: "region/TP"
    - RegionBasedFalsePositives:
        thresholds: 0.80
        IoU_threshold: 0.30
        resize_factor: 0.5
        name: "region/FP"
    - RegionBasedFalseNegatives:
        thresholds: 0.80
        IoU_threshold: 0.30
        resize_factor: 0.5
        name: "region/FN"
    - RegionBasedFBetaScore:
        thresholds: 0.80
        IoU_threshold: 0.30
        resize_factor: 0.5
        beta: 1.0
        name: "region/F1-score"
    - RegionBasedFBetaScore:
        thresholds: 0.80
        IoU_threshold: 0.30
        resize_factor: 0.5
        beta: 2.0
        name: "region/F2-score"
