model: UNetAnnotator
model_options:
    n_filters_first: 64
    n_downsample: 4
    rate: 2
    kernel_size: 3
    conv_stride: 1
    bn: true
    padding: same
    activation:
        class_name: LeakyReLU
        config:
            alpha: 0.3
