model: UNetAnnotator
model_options:
    n_filters_first: 3
    n_downsample: 3
    rate: 2
    kernel_size: 3
    conv_stride: 1
    bn: false
    padding: same
deploy_options:
    optimizer: adam
    loss: mse
data_options:
    batch_size: 4
    buffer_size: 2048
