model: UNetAnnotator
model_options:
    n_filters_first: 3
    n_downsample: 3
    rate: 2
    kernel_size: 3
    conv_stride: 1
    bn: false
    padding: same
deploy_options:
    optimizer: adam
    loss:
        name: WeightedCrossentropy
        option:
            weight_mul: 3.0
    metrics:
        - Precision:
            thresholds: 0.80
        - Recall:
            thresholds: 0.80
        - AUC:
            curve: "PR"
            name: "pixel/AUPRC"
        - AUC:
            curve: "ROC"
            name: "pixel/AUROC"
    enable_multigpu: false
data_options:
    train:
        batch_size: 8
        buffer_size: 256
        normalize_exams: true
        output_size: [256, 256]
        slice_types: ['TRA', 'ADC', 'DWI', 'DCEE', 'DCEL', 'label']
    eval:
        batch_size: 64
        output_size: [256, 256]
        slice_types: ['TRA', 'ADC', 'DWI', 'DCEE', 'DCEL', 'label']
