model: UNetAnnotator
model_options:
    n_filters_first: 3
    n_downsample: 3
    rate: 2
    kernel_size: 3
    conv_stride: 1
    bn: false
    padding: same
deploy_options:
    optimizer: adam
    loss:
        name: WeightedCrossentropy
        option:
            weight_mul: 3.0
    enable_multigpu: false
data_options:
    train:
        batch_size: 8
        buffer_size: 256
        normalize_exams: true
    eval:
        batch_size: 64
